name: Create GitHub release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Parse changelog
      uses: ./
      id: parse-changelog
      with:
        version: ${{ github.ref_name }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: '${{ github.ref_name }}'
        body: '${{ steps.parse-changelog.outputs.body }}'